### ISSUE TITLE
Manually updating sprite's position

### ISSUE THREAD

**Issue by larsonjj** [lewster32/phaser-plugin-isometric#24]
Hello,

I'm running into an issue where I need to update a sprite's isoPosition at a specific time interval. Basically I'm communicating a sprites position to a Node server from different browser clients and verifying those positions via websocket at a consistent time interval.

For example, I can replicate the issue i'm seeing if I add the following code snippet after line 80 for the example on: [http://rotates.org/phaser/iso/examples/character.htm](http://rotates.org/phaser/iso/examples/character.htm)

```js
setInterval(function() {player.isoX = 128; player.isoY = 128}, 1000);
```

Once you move the cube sprite using the keyboard, you will see the sprite start to flicker and constantly change positions in a seemingly random fashion. 

It's super weird and I can't figure out how to resolve it.

Maybe their is a better way to update a sprite's position?

Awesome plugin BTW :+1:

**Comment by larsonjj** [comment]
I actually found a solution based on a [post you made](http://www.html5gamedevs.com/topic/10508-sprite-movement-movetoxy-vs-using-tween/) @lewster32 :+1: 

Basically, you need to set `player.body.moves = false` before making any updates to the `player.isoX` or `player.isoY` properties. Then after making the position updates, reset `player.body.moves = true`.

Hope this helps anyone else who runs into the same issues.

**Comment by lewster32** [comment]
Yeah - for reference, what's happening is the physics system when enabled tries to take control of the position of an object. If you manually change the position while the physics system is in control, all kinds of weirdness will happen, such as juddering or the object suddenly flying off in a direction. By setting body.moves = false, you tell the physics system to stop trying to move the object, and thus allow you to manually set the position. Once it's moved, you can re-enable it and the physics system will just resume from its new position.

**Comment by wassname** [comment]
Sorry for reviving this, and feel free to ignore this if your mind is in other places. 

One frequent issue is that sprites that are manually moved during update tend to flies off. This is because position has already been synced with isoPosition during preUpdate. Then isoPosition is set to cause a manual movement. The next stage is postUpdate a the difference between position and the new isoPosition is large, and is applied as a proxy for velocity.

Possible solutions are:
 - Check for phase===1 and manually call preUpdate (my preferred option)
 - Check for phase===1 and set to 2 to skip postUpdate on this sprite
 - Reset the sprite but then add the velocity again
 - use the interval _reset flag

Thoughts?

**Comment by lewster32** [comment]
All valid ways of doing it - I guess it's down to how you want to implement it. I'd usually avoid playing with the internal properties if I can, as they've usually been made internal for a good reason - though saying that on occasion there's no other way to go about it.

**Comment by wassname** [comment]
Thanks for the sanity check!
