### ISSUE TITLE
How to create an Iso player that follows mouse clicks?

### ISSUE THREAD

**Issue by deividkamui** [lewster32/phaser-plugin-isometric#27]
I want to move a player object based on the mouse events, is there any way to achieve this?

**Comment by mfpierre** [comment]
You can start with this example http://rotates.org/phaser/iso/examples/interaction.htm and then plug a path finding algorithm to control your sprite to the destination with severals tweens.
I'm planning to open source some work I've done about that when I find some time.

**Comment by lewster32** [comment]
Agree with @mfpierre on a worthwhile course of action - the question is rather wide-ranging and not really that specific to the isometric plug-in itself.

**Comment by deividkamui** [comment]
Sorry for not being specific.

I'm trying to move my character based on the interaction example combined with the camera follow example, but I'm not very sure if its is correct to use the body.position to move my player or use the body.velocity.

Which one is the best to use?

**Comment by lewster32** [comment]
If you want the object to move and stop at a position, the easiest way is to temporarily disable the body on the object, and then tween its isoX and isoY properties to the desired location (which you can determine via ```game.iso.unproject``` like in [this example](http://www.rotates.org/phaser/iso/examples/interaction.htm).

More likely is that you're wanting physics to be a factor, in which case you need to set the correct velocity values so that the object moves towards the point you have selected at the required speed, and stops when it reaches its destination, or a threshold within the distance of its destination, or gets stuck and cannot reach its destination - so it's not a trivial process!

It's probably worth looking at [this piece of code](https://github.com/photonstorm/phaser/blob/v2.4.3/src/physics/arcade/World.js#L1406) in Phaser's Arcade physics, as you're probably wanting to move on the X/Y plane anyway - so it should still work.

**Comment by wassname** [comment]
If anyone needs moveToXYZ, [here](https://gist.github.com/wassname/38cb3a69507a3af66900) is an implementation

**Comment by lewster32** [comment]
Cool :) Feel free to submit this as a PR if you'd like it included in the main branch!

**Comment by wassname** [comment]
Thanks! When I get time (perhaps Jan) I'll submit a PR which add isometric versions of a few of Phaser's Arcade physics's convenience methods.

**Comment by lewster32** [comment]
Great stuff, thank you! :+1:
